# Generated by Django 5.1.3 on 2024-12-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rentalrecord_customer_rentalrecord_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspace',
            name='daily_price',
        ),
    ]
